import React from 'react'
export const metadata = {
    title: "Home | Glife",
    description: "Generated by create next app",
  };
const Home = () => {
  return (
    <div>Home</div>
  )
}

export default Home